      
on:
  push:
    # Sequence of patterns matched against refs/tags
    #tags:
    #- 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    
name: Upload Release Asset 

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install flake8 pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install pypa/build
        run: |
            python -m pip install build
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          python -m build --sdist --wheel --outdir dist/.
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PYCTBN_TOK }}
        with:
          tag_name: ver.${{ github.ref }}
          release_name: Release ver. ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PYCTBN_TOK }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          assets_path: ./dist
